language: go
go:
  - master

before_install:
  - go get github.com/mattn/goveralls

script:
  - make test

deploy:
  skip_cleanup: true
  provider: script
  script: make coverall
  on:
    repo: senseyeio/diligent
    branch: master

sudo: required
services:
  - docker